'use strict';
const $=id=>document.getElementById(id),e=SBMSASchedules.escapeHTML;
let data=null,view='rainbow-unicorns',filter='Upcoming';
const fmt=n=>n===null?'—':(n>0?'+':'')+Number(n.toFixed(2));
function render(){if(!data)return;
 const all=SBMSARatings.compute(data.divisions,'5ug',data.ratingMode||'raw'),division=$('division').value,q=$('search').value.trim().toLowerCase();
 const shown=all.filter(t=>(division==='all'||t.division===division)&&(t.team+' '+(t.coach||'')).toLowerCase().includes(q));
 $('count').textContent=shown.length+' / '+all.length+' teams';
 $('rows').innerHTML=shown.map(t=>{const followed=t.division==='Boxx'&&t.team==='Rainbow Unicorns',scoredGP=t.scored_gp??t.gp,margin=scoredGP?(data.ratingMode==='capped'?t.capped_margin_sum:t.margin_sum)/scoredGP:null;return `<div class="row ${followed?'favorite':''}" data-team="${e(t.team)}" data-division="${e(t.division)}" data-rank="${t.rank||''}"><span class="rank">${t.rank?t.rankText:'—'}</span><div><div class="team">${e(t.team)}${followed?'<span class="chip" aria-label="Followed team" title="Followed team">●</span>':''}</div><div class="coach">Coach: ${e(t.coach||'Not listed')}</div><div class="division">${e(t.division)} · ${t.rank?t.gp+' played':'Unrated'}${t.outcome_only_gp?` · ${scoredGP} scored / ${t.gp} GP · score unavailable`:''}</div></div><span class="record">${t.w}–${t.l}–${t.t}</span><span class="result">${fmt(margin)}</span><span class="diff ${t.power>=0?'pos':'neg'}">${t.power===null?'—':fmt(t.power)}</span></div>`;}).join('')||'<p>No teams match.</p>';
 const games=SBMSALeagueSchedule.filterRows(SBMSALeagueSchedule.buildRows(data,'5ug'),{division,query:q,filter});$('schedule-count').textContent=games.length+' fixtures';$('schedule-rows').innerHTML=SBMSALeagueSchedule.renderRows(games);
 const rainbow=SBMSARainbowSchedule.buildRows(data);
 $('rainbow-schedule-count').textContent=rainbow.length+' fixtures · '+rainbow.filter(r=>r.completed).length+' final · '+rainbow.filter(r=>!r.completed).length+' unplayed';
 $('rainbow-schedule-rows').innerHTML=SBMSALeagueSchedule.renderRows(rainbow,{showStatus:true});
 $('rainbow-schedule-mode').textContent=data.ratingMode==='capped'?'3-goal cap':'Raw';
 SBMSARainbow.render(data,$('rainbow-unicorns'));
}
function setView(next){if(!['rainbow-unicorns','rainbow-schedule','rankings','league-schedule'].includes(next))next='rainbow-unicorns';view=next;document.body.dataset.view=view;document.querySelectorAll('[data-view]').forEach(b=>{if(b===document.body)return;const active=b.dataset.view===view;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$(b.dataset.view).hidden=!active;});$('shared-filters').hidden=['rainbow-unicorns','rainbow-schedule'].includes(view);render();}
document.querySelectorAll('.section-links [data-view]').forEach(b=>{b.onclick=()=>{location.hash=b.dataset.view;setView(b.dataset.view);};b.onkeydown=event=>{const tabs=[...document.querySelectorAll('.section-links [data-view]')];let i=tabs.indexOf(b);if(event.key==='ArrowRight')i=(i+1)%tabs.length;else if(event.key==='ArrowLeft')i=(i+tabs.length-1)%tabs.length;else if(event.key==='Home')i=0;else if(event.key==='End')i=tabs.length-1;else return;event.preventDefault();tabs[i].click();tabs[i].focus();};});
for(const mode of ['raw','capped'])$(mode).onclick=()=>{if(!data)return;data.ratingMode=mode;for(const m of ['raw','capped'])$(m).setAttribute('aria-pressed',String(mode===m));render();};
$('division').onchange=render;$('search').oninput=render;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});
window.onhashchange=()=>setView(location.hash.slice(1));setView(location.hash.slice(1));
(async()=>{try{const fetchJSON=async url=>{const r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(url+' HTTP '+r.status);return r.json();};const [d,p,provenance]=await Promise.all(['./data.json','./soccer-projections/current.json','./export.json'].map(fetchJSON));if(d.divisions.length!==2||!d.divisions.every(x=>x.sport==='5ug')||p.generated_at!==d.last_successful_check||p.model.prior_games!==3)throw Error('Published subset/model mismatch');data=d;data.ratingMode='raw';data.soccerProjections=p;const ct=s=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',dateStyle:'medium',timeStyle:'medium'}).format(new Date(s))+' CT';const stale=Date.now()-Date.parse(d.last_successful_check)>12*3600000;$('publication').innerHTML=`<strong>${d.status==='ok'?'Source check OK':'Source check error — last accepted results'}${stale?' · Stale source':''}</strong><details><summary>Publication details</summary><p>Source checked: ${e(ct(d.last_checked))}<br>Last successful source: ${e(ct(d.last_successful_check))}<br>Results changed: ${e(ct(d.data_updated))}<br>5U export: ${e(ct(provenance.exported_at))}</p></details>`;$('sources').innerHTML=d.divisions.map(x=>`<li><a class="method-link" target="_blank" rel="noopener noreferrer" href="${e(SBMSASchedules.safeSourceURL(x.url))}">${e(x.division)} official standings &amp; schedule</a></li>`).join('');render();setInterval(()=>SBMSARainbow.render(data,$('rainbow-unicorns')),1000);}catch(err){$('publication').textContent='Unable to load verified 5U publication: '+err.message;$('publication').classList.add('status-error');}})();
